name: mobile_pad_pa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+43

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  uni_links: ^0.5.1
  flutter_svg:
  url_launcher: ^6.2.6
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  flutter_secure_storage: 9.0.0
  flutter_secure_storage_windows: 3.0.0
  english_words: ^4.0.0
  intl:
  google_fonts: ^6.2.1
  js: ^0.6.7
  flutter_time_picker_spinner: 2.0.0
  table_calendar: ^3.0.0
  go_router: ^12.0.1
  dropdown_search: ^5.0.5
  pinput: ^4.0.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  getwidget: ^4.0.0
  web_socket_channel: ^2.1.0
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_analytics: ^11.2.0
  flutter_local_notifications: ^17.2.2
  cached_network_image: ^3.2.1
  overlay_support: ^2.1.0
  curved_labeled_navigation_bar: ^2.0.2
  convex_bottom_bar: ^3.2.0
  image_picker: ^0.8.7+3
  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/pa_logo_2.jpg"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    -  assets/images/ # Vos ressources d'images ici

